### ISSUE TITLE
Windows, works manually with protoc on WSL and CMD, but I geta permission denied error when building with cargo

### ISSUE THREAD

**Issue by brandonpollack23** [mtp401/protoc-grpcio#15]
Here's my repo (ignore the state it's it, im transitioning it from grpc-rust to try things out):
https://github.com/brandonpollack23/rustchat

Here's the error:
```
C:\Users\brandon\AppData\Local\Temp\.tmpRoIDe7: Permission denied
thread 'main' panicked at 'Failed to compile gRPC protos: Custom { kind: Other, error: StringError("protoc exited with non-zero exit code") }

stack backtrace:
   0: failure::backtrace::internal::InternalBacktrace::new (0x7ff7167aa6b3)
             at C:\Users\brandon\.cargo\registry\src\github.com-1ecc6299db9ec823\failure-0.1.3\src\backtrace\internal.rs:44
   1: failure::backtrace::Backtrace::new (0x7ff7167a955e)
             at C:\Users\brandon\.cargo\registry\src\github.com-1ecc6299db9ec823\failure-0.1.3\src\backtrace\mod.rs:111
   2: failure::error::error_impl::{{impl}}::from<std::io::error::Error> (0x7ff71675c7d0)
             at C:\Users\brandon\.cargo\registry\src\github.com-1ecc6299db9ec823\failure-0.1.3\src\error\error_impl.rs:19
   3: failure::error::{{impl}}::from<std::io::error::Error> (0x7ff71675c3bf)
             at C:\Users\brandon\.cargo\registry\src\github.com-1ecc6299db9ec823\failure-0.1.3\src\error\mod.rs:36
   4: core::convert::{{impl}}::into<std::io::error::Error,failure::error::Error> (0x7ff71676469f)
             at \libcore\convert.rs:456
   5: failure::context::Context<str*>::with_err<str*,std::io::error::Error> (0x7ff71675f67f)
             at C:\Users\brandon\.cargo\registry\src\github.com-1ecc6299db9ec823\failure-0.1.3\src\context.rs:105
   6: failure::Fail::context<std::io::error::Error,str*> (0x7ff716764791)
             at C:\Users\brandon\.cargo\registry\src\github.com-1ecc6299db9ec823\failure-0.1.3\src\lib.rs:154
   7: failure::result_ext::{{impl}}::context::{{closure}}<(),std::io::error::Error,str*> (0x7ff71676448b)
             at C:\Users\brandon\.cargo\registry\src\github.com-1ecc6299db9ec823\failure-0.1.3\src\result_ext.rs:164
   8: core::result::Result<(), std::io::error::Error>::map_err<(),std::io::error::Error,failure::context::Context<str*>,closure> (0x7ff71675b7e2)
             at \libcore\result.rs:530
   9: failure::result_ext::{{impl}}::context<(),std::io::error::Error,str*> (0x7ff716758fdf)
             at C:\Users\brandon\.cargo\registry\src\github.com-1ecc6299db9ec823\failure-0.1.3\src\result_ext.rs:165
  10: protoc_grpcio::compile_grpc_protos<[str*; 1]*,[str*; 1]*,str*> (0x7ff716754e40)
             at C:\Users\brandon\.cargo\registry\src\github.com-1ecc6299db9ec823\protoc-grpcio-0.3.1\src\lib.rs:225
  11: build_script_build::main (0x7ff716764da7)
             at C:\Users\brandon\CLionProjects\rustchat\build.rs:4
  12: std::rt::lang_start::{{closure}}<()> (0x7ff7167516b0)
             at \libstd\rt.rs:74
  13: std::panicking::try::do_call<closure,i32> (0x7ff716a393e7)
             at /rustc/b6c32da9b0481e3e9d737153286b3ff8aa39a22c\src/libstd\panicking.rs:310
  14: panic_unwind::__rust_maybe_catch_panic (0x7ff716a447b2)
             at /rustc/b6c32da9b0481e3e9d737153286b3ff8aa39a22c\src/libpanic_unwind\lib.rs:102
  15: std::rt::lang_start_internal (0x7ff716a27c83)
             at /rustc/b6c32da9b0481e3e9d737153286b3ff8aa39a22c\src/libstd\rt.rs:58
  16: std::rt::lang_start<()> (0x7ff71675168b)
             at \libstd\rt.rs:74
  17: main (0x7ff716764e00)
  18: __scrt_common_main_seh (0x7ff716a5360c)
             at f:\dd\vctools\crt\vcstartup\src\startup\exe_common.inl:283
  19: BaseThreadInitThunk (0x7fff3b1c3034)
```

**Comment by brandonpollack23** [comment]
Just a heads up, more investigation definitely leads me to believe the temp file is never being created by the tempfile crate.

**Comment by mattiasbrand** [comment]
I had the same issue and it works when I downgrade to 0.3.0. 

I see that one major difference between 0.3.0 and 0.3.1 is the switch from mktemp to tempfile.

**Comment by tyan-boot** [comment]
see [tempfile #76](https://github.com/Stebalien/tempfile/pull/76)

currently only downgrade to 0.3.0 before tempfile release a new version.

**Comment by mtp401** [comment]
Hello, tempfile has release 3.0.6 which includes the fix for this issue. I've updated tempfile accordingly and have pushed 1.0.1 to crates.io.
