### ISSUE TITLE
"No such file or directory"

### ISSUE THREAD

**Issue by marcelbuesing** [mtp401/protoc-grpcio#9]
gRPC compilation fails in a docker container see below how to reproduce this.

`Dockerfile` to reproduce run with

docker build -t grpcio-temp .

```
FROM liuchong/rustup:nightly
RUN apt-get update && \
    apt-get install --no-install-recommends -y \
   cmake \
   golang \
   protobuf-compiler \
   protobuf-compiler \
   git

RUN git clone https://github.com/mtp401/protoc-grpcio.git
RUN cd protoc-grpcio/example && RUST_BACKTRACE=1 cargo test -vv
```

```
error: failed to run custom build command for `example v0.0.1 (/root/protoc-grpcio/example)`
process didn't exit successfully: `/root/protoc-grpcio/example/target/debug/build/example-1877cef8f11f8b15/build-script-build` (exit code: 101)
--- stdout
cargo:rerun-if-changed=src/protos

--- stderr
example/diner.proto: No such file or directory
thread 'main' panicked at 'Failed to compile gRPC definitions!: Custom { kind: Other, error: StringError("protoc exited with non-zero exit code") }

stack backtrace:
   0:     0x562bed5f3745 - backtrace::backtrace::libunwind::trace::hdbc277b57fee3187
                        at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.8/src/backtrace/libunwind.rs:53
                         - backtrace::backtrace::trace::h9517ed56f5dfdeaf
                        at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.8/src/backtrace/mod.rs:42
   1:     0x562bed5e8f7e - backtrace::capture::Backtrace::new_unresolved::h8c3ae1e0a94d4235
                        at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.8/src/capture.rs:88
   2:     0x562bed5e7443 - failure::backtrace::internal::InternalBacktrace::new::h2bc18afefecc8700
                        at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/failure-0.1.1/src/backtrace/internal.rs:44
   3:     0x562bed5e688c - failure::backtrace::Backtrace::new::h97a09cb570137c12
                        at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/failure-0.1.1/src/backtrace/mod.rs:98
   4:     0x562bed5aa34d - <failure::error::Error as core::convert::From<F>>::from::h6d07176afbacf89e
                        at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/failure-0.1.1/src/error.rs:34
   5:     0x562bed5b862e - <T as core::convert::Into<U>>::into::hcd7d6c71dee3a8b8
                        at libcore/convert.rs:456
   6:     0x562bed5b7568 - <failure::context::Context<D>>::with_err::hf3e8e69a867be956
                        at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/failure-0.1.1/src/context.rs:78
   7:     0x562bed5b86cc - failure::Fail::context::h89f9f49cf0492ee5
                        at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/failure-0.1.1/src/lib.rs:127
   8:     0x562bed5b8b39 - <core::result::Result<T, E> as failure::result_ext::ResultExt<T, E>>::context::{{closure}}::h713b413aed581568
                        at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/failure-0.1.1/src/result_ext.rs:32
   9:     0x562bed5b0594 - <core::result::Result<T, E>>::map_err::h35212bb56ba02206
                        at libcore/result.rs:530
  10:     0x562bed5adfbd - <core::result::Result<T, E> as failure::result_ext::ResultExt<T, E>>::context::h1225d02a64e9630d
                        at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/failure-0.1.1/src/result_ext.rs:32
  11:     0x562bed5b35c2 - protoc_grpcio::compile_grpc_protos::h2ccd84404bb8aada
                        at /root/protoc-grpcio/src/lib.rs:224
  12:     0x562bed5a4ef1 - build_script_build::main::h3e9df73dbd448825
                        at /root/protoc-grpcio/example/build.rs:6
  13:     0x562bed5b7f9f - std::rt::lang_start::{{closure}}::h9d45ed3ec5f9be81
                        at libstd/rt.rs:74
  14:     0x562bed887f62 - std::rt::lang_start_internal::{{closure}}::hfb96f2c3e3e3ca27
                        at libstd/rt.rs:59
                         - std::panicking::try::do_call::hb5c650dad7b54bc8
                        at libstd/panicking.rs:310
  15:     0x562bed8a8459 - __rust_maybe_catch_panic
                        at libpanic_unwind/lib.rs:102
  16:     0x562bed893505 - std::panicking::try::hfdbf960f69164b7e
                        at libstd/panicking.rs:289
                         - std::panic::catch_unwind::ha86229f9b0fb2c07
                        at libstd/panic.rs:392
                         - std::rt::lang_start_internal::hbe298169bff7a199
                        at libstd/rt.rs:58
  17:     0x562bed5b7f77 - std::rt::lang_start::h283127b68027dc0d
                        at libstd/rt.rs:74
  18:     0x562bed5a4f59 - main
  19:     0x7fbc80abf2e0 - __libc_start_main
  20:     0x562bed5a4cf9 - _start
  21:                0x0 - <unknown>
```

**Comment by marcelbuesing** [comment]
Thanks for so releasing the new version so quickly!
